# Generated by Django 3.2 on 2023-02-28 15:07

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hostname', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('rhost', models.GenericIPAddressField(blank=True, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('is_successful', models.BooleanField(default=True)),
            ],
        ),
    ]
