# Generated by Django 3.2.18 on 2023-03-24 05:14

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='is_suspicious',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BlackListRule',
            fields=[
                ('rule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='records.rule')),
            ],
            bases=('records.rule',),
        ),
        migrations.CreateModel(
            name='WhiteListRule',
            fields=[
                ('rule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='records.rule')),
            ],
            bases=('records.rule',),
        ),
    ]
