# Generated by Django 3.2.18 on 2023-03-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20230324_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='rhost',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
