# Generated by Django 3.2.18 on 2023-03-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_rule_rhost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='rhost',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
