# Generated by Django 3.2.18 on 2023-03-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_alter_rule_rhost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='rhost',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
