# Generated by Django 3.2.18 on 2023-03-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='telegram_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
